# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170704_1350'),
        ('blog', '0002_auto_20170703_1759'),
    ]

    operations = [
    ]
